### ISSUE TITLE
Sankey weaver 

### ISSUE THREAD

**Issue by alexcolloricchio** [ricklupton/floweaver#62]
Hi,

I am a beginner Python user and I am experimenting with Floweaver for the first time so sorry if my question is badly posed or incomplete.

I am running Python 3.6 with all floweaver dependencies (pandas and numpy) updated in the working environment, however I cannot visualise the output on my local machine. Any idea what the issue might be?

Thank you

**Comment by ricklupton** [comment]
Hi, have you followed the [Getting Started section](https://github.com/ricklupton/floweaver#get-started-using-floweaver) of the README -- especially the bit about enabling `ipywidgets` and `ipysankeywidget`?

**Comment by alexcolloricchio** [comment]
Hi Rick,

Yes I did, in fact I can visualise the Sankeys on my Jupyter notebooks but not on my python console. Is the software designed to visualise the diagrams only on Jupyter?

**Comment by anamarta** [comment]
I have the same problem. I followed the instructions for installation and the Quick tutorial but I cannot visualize the plots.

**Comment by ricklupton** [comment]
@alexcolloricchio @anamarta Yes, the examples all assume you're working in the Jupyter notebook. This is because the Sankey diagrams are actually rendered by the library [d3-sankey-diagram](https://github.com/ricklupton/d3-sankey-diagram) via [ipysankeywidget](https://github.com/ricklupton/ipysankeywidget), which need to run in the browser.

It's possible to use floWeaver outside of Jupyter notebook, but this is less well documented at the moment. See #34.
