### ISSUE TITLE
Using floweaver outside of jupyter notebooks

### ISSUE THREAD

**Issue by clbarnes** [ricklupton/floweaver#78]
Jupyter notebooks make up only a tiny fraction of all python usage, and the documentation states

> The **best** way to get started is to use it in a Jupyter notebook (although it is just a Python package, so you are free to use it however you wish).

This, plus the fact that `ipysankeywidget` is not a dependency of the package, suggests that it is possible to use floweaver outside of the jupyter notebook. However, I can't find any information on how to do so.

If floweaver cannot be used to draw sankey diagrams with python, this needs to be called out front and center in the documentation, and the dependencies need to be specified properly. Otherwise, it needs some documentation saying how it can be used in normal python.

**Comment by ricklupton** [comment]
Thanks for all the comments and the pull request! I'll take a look as soon as I can.

It is possible to use floweaver without the Jupyter notebook by exporting the Sankey data as JSON then using my svg-sankey tool to convert to SVG (see [this comment](https://github.com/ricklupton/floweaver/issues/34#issuecomment-385040059)). I agree this isn't well documented at the moment which is partly because I'm not yet happy that the JSON format is right and I wasn't wanting to commit to it... but usually waiting for things to be finished is not a good reason not to document them!

Ideally in the end there could be a floweaver export function that takes care of running svg-sankey for you, perhaps also bundling the nodejs script with the Python package but I don't know if that's a good idea.
